### ISSUE TITLE
MVP gene set DB selection

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#10]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

We need to select a gene set DB for the algorithm so that users don't have to choose one.

- For the MVP, choose a good default for user, human only
- The user can't change which DB is used.  It's fixed
- Current one: `Human_GOBP_AllPathways_no_GO_iea_June_01_2022_symbol.gmt`
- Human, gene symbols, pathway subset
- Include name of DB in service JSON output

**Motivation for new feature**

_Describe your use case for this new feature._

Required for the algorithm.  Users don't want to or know how to choose one.

**Comment by maxkfranz** [comment]
@veroniquevoisin & @risserlin, would you please give us a suggestion of the best human DB to use as a default?

**Comment by risserlin** [comment]
Is it static or can it be updated to the latest gmt file on the fly?

**Comment by maxkfranz** [comment]
I think Mike made it static for now, right @mikekucera?

**Comment by veroniquevoisin** [comment]
I always use the latest release for each new analysis: http://download.baderlab.org/EM_Genesets/current_release/Human/symbol/Human_GOBP_AllPathways_no_GO_iea_August_03_2022_symbol.gmt
Therefore it would make more sense in my opinion that it is not static, however I don't know the technical efforts required for it.

**Comment by mikekucera** [comment]
It would be a major feature to make the DB dynamic. 
One approach would be to somehow notify all the services when there's a new DB, and they would all have to download it. Another approach would be to make it part of the build process to bundle a new DB with the services, then create and push new versions of the services.
We would also need UI for allowing the user to select a DB, or at least show which DB was used.

**Comment by maxkfranz** [comment]
> Another approach would be to make it part of the build process to bundle a new DB with the services, then create and push new versions of the services.

This seems like the simplest solution.  If the services are updated in lockstep frequently enough, then they'll be new enough for users without them having to make selections.  

Eventually, this could be automated with GitHub Actions with whatever release cadence we prefer.

The build approach is preferable when considering citations and reproducibility.  Build versions can be cited by version and DOI.  Dynamic, automatically-updated-on-the-fly services can not.

> We would also need UI for allowing the user to select a DB, or at least show which DB was used.

This could fit well into both the front query page and the export.

**Comment by maxkfranz** [comment]
I think this is done for MVP

Let's keep this open until we create a new issue for longterm discussion of updating and maintenance for the gene set DB.
