### ISSUE TITLE
Open the sidebar when clicking a node

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#100]
**Description of new feature**

- When a node is clicked (i.e. selected), open the sidebar if it’s not open already.
- The sidebar already flashes a bit because of the loading indicator for the gene list, so the sidebar may be salient enough already for the case where you click a node with the sidebar already open.

**Motivation for new feature**

- Users want to see the genes when they click a node.
- The sidebar might have been closed by the user before clicking a node.  Clicking the node in this case is confusing.  Nothing happens.
- #88

**Comment by chrtannus** [comment]
Should the sidebar be opened automatically on small screens (e.g. iPhone) as well?
In that case, the "floating" sidebar will probably hide the selected node.

<img width="280" src="https://user-images.githubusercontent.com/989686/232074220-62ee41d3-ad90-45c0-bf70-30e875bd42a7.gif" />

**Comment by maxkfranz** [comment]
Summary:

- How about disabling automatically opening the sidebar for small-screen devices?
- Optional enhancement:  If you click an already selected node, then you can open the sidebar.

Explanation:

In the short term, I don't think we need to worry too much about mobile.  It's important in the medium-to-long-term.  One of the people I spoke with wanted to pull up the app on their phone as soon as they started using the app:  "I'd spend my time looking at the app while I'm commuting on the subway, so I want to confirm that it would work on my phone."  I didn't mention this before, because it's not worth obsessing over for now.

So, I don't think we need a perfect solution for now.  We just need something that's sufficient, and we can improve on it later.

If we go forward with the automatic zoom (#105) -- which is useful on mobile, where you have less screen space -- then automatically opening the sidebar on tap isn't great:  You tap, because you want to see more.  You couldn't even read the labels before you tapped, because they're so small when zoomed out, so you click to zoom in.  But everything gets hidden by the sidebar.  You don't even know what you clicked, so you don't know what the info in the sidebar is for.

So, maybe the simplest thing for now is to not automatically open the sidebar when tapping a node only if you're on a small-screened device.  The user could open the sidebar manually after that, or we could offer a simple feature addition:  If you tap on a node when it's already selected, it opens the sidebar.

**Comment by chrtannus** [comment]
Good reasoning, Max.
I disabled the automatic opening for small-screen devices.
I'm not sure about the optional enhancement (click again to open it), so let's keep it simple for now.

**Comment by maxkfranz** [comment]
Great.  Let's leave this open for now.  I'll create a new issue for the open-on-second-tap idea, so we can consider it later on when we're focussing more on mobile.  After I post that new issue, I'll close this one.

**Comment by maxkfranz** [comment]
New issue: Method to conveniently open the genes sidebar on mobile #111
