### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#11]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

- Build a front page that allows the user to submit a query.
- Incl. an upload button.  After the file is selected, the query is submitted.
- Show a loading spinner, that replaces the upload button, when the query is submitted.
- Error message on file error.

Depends on:

- #12 
- #13 
- #8 

**Motivation for new feature**

_Describe your use case for this new feature._

Provide a place for the user to start a query.

**Comment by mikekucera** [comment]
There were two issues called "front page". I changed the other one (#3) to be about making the front page look good and provide meaningful text for the user. This issue will just be for the functionality of ranked gene list upload and progress spinner.

**Comment by maxkfranz** [comment]
- Mobile support #31 
- Future:  Describe the use case better
- Future:  Example end-to-end network / paper / data -- reproducible, maybe even a DOI with the files from the original paper
- Idea:  Simple image of a (ranked gene list => network) figure that shows conceptually what's happening
- Photoshop mockup
- Text box input?

**Comment by maxkfranz** [comment]
Add a debug menu for sample files.
