### ISSUE TITLE
Ensembl ID support

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#112]
**Description of new feature**

- Add support for Ensembl IDs.
- If a user has Ensembl IDs in their input file, then the app should report those genes naturally in the sidebar.  
- E.g. if a user has `ENSG00000232810` as a gene, then the UI should show the gene name ‘TNF’ (some popular synonym):  http://useast.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000232810;r=6:31575565-31578336
- Suggestion:  Just use BridgeDB for now: https://www.bridgedb.org/
- Future, if & as needed:  We may use gProfiler for ID mapping when old versions of the IDs are used: https://biit.cs.ut.ee/gprofiler/gost

**Motivation for new feature**

- A significant proportion of users will use Ensembl IDs.
- Users don’t know the IDs.  They can’t read IDs in the sidebar.  They need to see the common name.

**Comment by mikekucera** [comment]
I noticed the sample file from Ruth has Ensembl IDs in the first column and HGNC names in the second column. We wouldn't have to map the genes in that case if we asked the user to choose which column to use for gene names. (Note currently you have to click "ignore" in the class chooser for the HGNC column or it returns an error.) We could continue to mandate that the first column is gene name and use bridgedb to map the genes, the results would probably be the same. What do you think?

**Comment by maxkfranz** [comment]
Ruth’s example is a bit of an ideal file from a course.  I a bit doubtful that a ‘real’ file would have both Ensembl and common names.  Probably, it would have one or the other.

General Ensembl/BridgeDB support might handle some edge cases transparently, but I haven’t thought about it that deeply yet.

**Comment by mikekucera** [comment]
Yeah. The client could just detect that the second column contains strings and auto-ignore it. I'm just going to continue with what I was doing.

**Comment by mikekucera** [comment]
What should we do if a Ensembl ID couldn't be mapped, remove it? 
If so should we warn the user about genes that couldn't be mapped?

**Comment by maxkfranz** [comment]
If it couldn't be mapped, then it could be one of the following cases:

(1) The ID is just invalid.

(2) The ID is valid and old, so BDB didn't pick it up.

We can't really differentiate (1) from (2) at this point, so it might be safest to keep the gene, display it by its ID in the panel, and log an error in Sentry so we can track it.

**Comment by mikekucera** [comment]
I'm not sure I agree. Mixing Ensembl and HGNC ids in the UI will look messy. Also we probably shouldn't pass the ensembl ids to the fgsea service because they won't be in any of the gene sets, and I'm not sure how that effects the algorithm. 

Perhaps just remove the invalid IDs for now and log in sentry?

Maybe we could show an warning icon somewhere (toolbar, top of gene panel?) and when the user clicks it, it shows a tooltip that says something like "10 ids from input file could not be found". It would also be good to tell the user the IDs that were invalid and the line numbers in the input file, in case the user cares to fix the problem.

**Comment by maxkfranz** [comment]
Let's discuss this tomorrow.  I agree that there's a balance to be struck between user intent, the algorithm, and UI feedback.

**Comment by maxkfranz** [comment]
TODO empty empty network issue

**Comment by maxkfranz** [comment]
Empty network issue: #46
