### ISSUE TITLE
Make it clear that Group B is the control

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#115]
**Description of new feature**

Update the class chooser UI so that its clear to the user that Group B is the control.
Note: This is based on the updated ranks calculation that uses the QL test.

**Motivation for new feature**

User needs to know which group is the control, so they know what UP and DOWN means because that's relative to the control.

**Comment by maxkfranz** [comment]
I think that's good for now.  If we need more improvements in future, we can find those with user feedback.  We haven't yet tested the upload UI at all with users, so there are some unknowns there.
