### ISSUE TITLE
Post-milestone planning

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#117]
Topics to discuss at the end of this milestone to plan future efforts:

- Performance improvements
  - Algorithm
  - Services
  - ... 
- Further user testing
- Emailing prospective users to try the app independently (max. 6)
- A 'beta' release
- Other use cases
- Refactoring (esp. re. reuse & fragility)
- Pipeline/algorithm review
- Refining
- Testing
  - Automated
  - Manual
- Download more (e.g. TSV)
- ...

Feel free to edit this with changes or new bullet points.

**Comment by mikekucera** [comment]
We should eventually take a pass over the codebase and cleanup/refactor parts that would benefit from it. For example the NetworkEditor component could be rewritten to use hooks.
