### ISSUE TITLE
FGSEA service

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#12]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

Allow the FGSEA algorithm to be used as a service.

- TODO requirements...
- ...

**Motivation for new feature**

_Describe your use case for this new feature._

GSEA is an important piece of the algorithm.

**Comment by maxkfranz** [comment]
@mikekucera, any outstanding requirements for this in particular?

**Comment by mikekucera** [comment]
No.

**Comment by maxkfranz** [comment]
Ref: [Reliability issues on Digital Ocean App Engine?](https://github.com/cytoscape/fgsea-service/issues/1)
