### ISSUE TITLE
Clicking the CANCEL button does not cancel the EM process

### ISSUE THREAD

**Issue by chrtannus** [cytoscape/enrichment-map-webapp#123]
**Describe the bug**
Clicking the CANCEL button on the _Loading_ dialog closes the dialog but it still creates a network and redirects to the editor.

**To Reproduce**
1. On the landing page, click the **GET STARTED** button
2. Upload a pre-ranked gene list (don't use a small file)
3. Click the **CANCEL** button on the _Loading_ dialog
4. Notice that the dialog closes but if you wait a little bit, it will redirect to the network page (or show the _Error_ dialog if the servers returns an error).

**Expected behavior**
Clicking the CANCEL button should interrupt the EM process (or at least not redirect to the EM network).
We should also purge cancelled networks from the database.

**Comment by mikekucera** [comment]
This relates to the issue about better progress reporting (#85). Perhaps we need to use something like a websocket to open a two-way communication between the client and the server, instead of using REST. This would enable the server to send back progress reports, and client could send a cancelation request.

**Comment by maxkfranz** [comment]
>  websocket to open a two-way communication between the client and the server

We could do that, but web sockets can get complicated and expensive.  They're great for live sync editing, like Google Docs.  For progress, you also have support in HTTP requests: https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent

For now, I think it's enough to just have a text message that lets the user know the loading screen is about a minute.

Another thing to consider is the fake progress bar with an estimate of the duration.  Those often feel like better UX (e.g. smoother progress).  A lot of popular systems just use the fake-it approach, like Gmail.

**Comment by maxkfranz** [comment]
Re. this issue specifically:  You could potentially mark networks as 'loaded' or 'viewed' once the user goes to the results view at least once.  That way, you have a way to distinguish a cancelled network from a finished network -- and cancelled networks could be deleted whenever (in a cron job, or based on some disk usage threshold, etc.).

**Comment by chrtannus** [comment]
In addition to the 'viewed' flag, maybe we should create an end point to delete a network/analysis.
The CANCEL button could call it right away and it may be useful in the future as well (e.g. the user wants to delete it from their "Recent Networks" list, which could also be another feature, by the way).

**Comment by maxkfranz** [comment]
Closing, as #126 was merged.  Please re-open if I've missed something
