### ISSUE TITLE
The Groups dialog should have a BACK button

### ISSUE THREAD

**Issue by chrtannus** [cytoscape/enrichment-map-webapp#125]
**Description of new feature**

Just add a BACK button to the **Groups** panel. Clicking the button returns to the **Upload your Data** panel.
<img width="50%" alt="back-button-screenshot" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/376b9d6b-f3d6-46a4-8081-b43aaf0e17fd">
 
**Motivation for new feature**

I'm getting tired of having to click CANCEL and then GET STARTED again when I upload the wrong file.
Of course, I'm testing different files all the time, so this is frequent for me, but I think that the same thing could happen to users. Besides, this ability to go back to the previous step is just a very common feature in wizards.

**Comment by maxkfranz** [comment]
That second option seems a bit more intuitive to me
