### ISSUE TITLE
Integrate clustering into EM service

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#13]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

- Integrate clustering
  - Use MCODE (or maybe some other algo.?) into this service for clustering/bubbles 
  - Assign a cluster ID per node.
- Integrate the WordCloud algorithm to be used for label generation.

Depends on:

- #10

**Motivation for new feature**

_Describe your use case for this new feature._

This is the main (top-level) algorithm service.

**Comment by mikekucera** [comment]
- Port MCODE clustering into the EM service
- Port WordCloud label generation into EM service. Hardcode reasonable defaults for MVP.

JSON output should include a cluster identifier for each node. Some nodes may be unclustered.
The result JSON should allow for multiple cluster identifiers to allow for new cluster algorithms to be added in the future that can be run simultaneously on the server.

**Comment by maxkfranz** [comment]
Generally, if it’s a straightforward issue, then it’s probably fine to just post updates in the issue and close it.

This one touches one at lot of other ones downstream, so I agree it would make sense to have a call like you suggested.
