### ISSUE TITLE
Minor style issue on home page in chrome

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#133]
**Describe the bug**
The area below the citation quote that says "App Authored By..." appears to have the wrong background color. Its grey but it looks like it should be black. This is in Chrome 112.

<img width="886" alt="Screenshot 2023-05-31 at 10 29 38 AM" src="https://github.com/cytoscape/enrichment-map-webapp/assets/5350528/32a0d1ca-bce1-41be-bc22-cc662c094303">

**Comment by chrtannus** [comment]
Fixed:

<img width="714" alt="authors-fixed" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/66cc212f-c361-498a-9bf1-41859bbea95d">
