### ISSUE TITLE
Upload wizard example ordering

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#135]
**Description of new feature**

It may be better to order the example files in the upload dialog with the expression file first.

**Motivation for new feature**

If expression is a more common format, then it's better to see that example first, without having to scroll.

**Comment by chrtannus** [comment]
**RNA-Seq Expression Data** is the first one now:

<img width="598" alt="upload-formats" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/fe524a53-88df-4b30-b0b8-63a0dafee8d7">
