### ISSUE TITLE
Why is green positive and purple negative?

### ISSUE THREAD

**Issue by risserlin** [cytoscape/enrichment-map-webapp#137]
green/blue is usually associated with down regulation not up regulation
<img width="1058" alt="Screen Shot 2023-06-02 at 10 48 17 AM" src="https://github.com/cytoscape/enrichment-map-webapp/assets/3842763/844b75bb-f468-4acc-8ef7-cbe495bbcb5d">

**Comment by risserlin** [comment]
red for up and blue for down.  But using the colours that you chose I would put purple as up and green as down.

**Comment by chrtannus** [comment]
So should we also use a red-blue color scheme as default?
This is the network with _ColorBrewer_'s [5-class RdBu](https://colorbrewer2.org/#type=diverging&scheme=RdBu&n=5):

<img width="750" alt="RdBu Network" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/c658aff0-1e65-4ae2-beff-3496491c1d40">

**Comment by maxkfranz** [comment]
Looks good

**Comment by risserlin** [comment]
Much better than the green/purple!  Thanks.
