### ISSUE TITLE
Query response size limiting for MVP

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#14]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

- Query responses can be large (i.e. large network).
- Large responses are bad UX:  Users don't want to wade through large networks, and large networks can be slow.
- Hard-coded filter element set N/size for MVP
- Perform filtering on the server (ideally in the originating service)
- Arbitrary p-val cut-off (e.g. EM defaults)

Depends on / part of:

- #12 
- #13

**Motivation for new feature**

_Describe your use case for this new feature._

Keep the response reasonable for a good UX.

**Comment by mikekucera** [comment]
EM Defaults...
- Nodes
  - p-value cutoff: 1.0 (basically no filtering on p-value)
  - q-value cutoff: 0.1
- Edges
  - similarity metric: COMBINED
  - combined constant: 0.5
  - similarity cutoff: 0.375

I tend to increase filtering on edges to avoid hairballs. A more stringent filtering would be...
  - similarity metric: JACCARD
  - similarity cutoff: 0.35

**Comment by mikekucera** [comment]
The fgsea service is not outputting a q-value. With the default EM options the filtering happens on q-value. Therefore no filtering is currently happening.

**Comment by mikekucera** [comment]
I made it so that the EM-service now has a parameter that can limit the number of enrichment results (ie nodes) that come out of the filtering step. It basically sorts them by qvalue (padj) and then takes the top X results. Then feeds them to the similarity task.

**Comment by maxkfranz** [comment]
- Currently using a q-value filter 0.1
- Strengthen this q-value threshold
- Process:  Throw slider so all nodes filtered out.  Shift the filter so nodes appear one by one.  Increase until you get the size you want.  Skim the cream from the top.
- Try client side filter where we simulate what a user would do with the slider
- Try a slider for experimentation
- Try just using a medium limit

**Comment by maxkfranz** [comment]
Log scale for colouring

**Comment by maxkfranz** [comment]
Cut it down to top 30 nodes based on q-value (lowest values)

**Comment by maxkfranz** [comment]
Filtering steps

- EM has a cutoff based on the qval
- Service cuts down to 800
- Then filter to 30

**Comment by mikekucera** [comment]
I added the filter on the client side. I set it to max 50 nodes, because 30 seemed really sparse, but you can change it if you like.
Note that the gene list still shows all the genes from the users input file when nothing is selected.
