### ISSUE TITLE
Show more pathway info

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#154]
**Description of new feature**

When a user taps on a pathway, they want to see more info about the pathway.

- Minimum: good linkout
- Summary
- Other info
  - Exact p-val
  - Related papers

**Motivation for new feature**

What's this pathway?

**Comment by maxkfranz** [comment]
Some users: What is this pathway?

**Comment by chrtannus** [comment]
See #198 and #197.
