### ISSUE TITLE
Sometimes much of the page can be selected

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#158]
**Describe the bug**

Sometimes, much of the page can be selected.  This makes a lot of the page highlighted in blue.  This feels broken.

Since this is an app, and not a page, it would be best to disable selection except in text boxes.  This is easy to do with CSS, but it might need workaround for Material UI.

**To Reproduce**

It's hard to reproduce.  Click around.  Maybe double click.

Or you could just drag select a bunch of stuff, starting with the sidebar.  You shouldn't be able to select anything that's not a text box.

**Expected behavior**

A random, accidental selection should not make the app look broken.  It can be hard to remove the selection.

**Screenshots**

None handy.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: latest
 - Safari
 - This is easier to reproduce here.

**Additional context**

So annoying.

**Comment by chrtannus** [comment]
I don't see the problem. Every web site is like that and users may want to select and copy/paste the gene list, etc.

**Comment by maxkfranz** [comment]
It's hard to reproduce.  Let's close this for now and re-open it if/when we can reproduce it reliably.

**Comment by chrtannus** [comment]
@maxkfranz Could you please test it again, specially on **iOS**? Text selection should now be disabled on most of the editor page, if not all of it (except text fields). It's already available on prod.

I've tested it on _Chrome_ (Win 11 and macOS), _Safari_ (macOS), _Firefox_ (macOS) and _Edge_ (Win 11).
