### ISSUE TITLE
Clearer genes panel contents

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#164]
**Description of new feature**

- Clarify what the genes in the sidebar correspond to.
  - Add a line of text in the scrollable area of the gene list at the top.  This way, it doesn't take up space when you scroll around. It can be the same size as a gene entry so that the scrolling performance library still works.
  - The line should be explicit: 'Genes in pathways X and Y' or 'Genes in pathway X'
  - What kind of genes?  All genes?  Significant genes?  Genes in the leading edge?
- Optional: The icon that shows what's selected (e.g. Venn diagram icon) could be highlighted in the same blue selection colour to make it more salient when a selection is made.

**Motivation for new feature**

- It's still not clear.
- People don't notice the icon.

**Comment by maxkfranz** [comment]
If I recall correctly:  Most traditional figures have edges within a cluster, but not between clusters.

Some users have said they want all the nodes connected by edges in our figures to be merged.

Anyway, there's still a general communication issue even outside of edges.  Let's just consider nodes:  We have genes in this pathway.  What genes in this pathway?  All of them?  The significant ones?  The leading edge (this one is only asked by advanced users)?

**Comment by mikekucera** [comment]
We shouldn't merge nodes that don't pass our similarity test, that would give incorrect results. It would be better to remove the leftover edges if the users don't want them. If we prune the network down to just 20 nodes there won't be very many edges left either.

**Comment by maxkfranz** [comment]
No selection: All genes

1 node selected: Genes in pathway

N nodes selected: Genes in N pathways

**Comment by maxkfranz** [comment]
https://github.com/PathwayCommons/app-ui/blob/05ea8b9a0a7256f5c01bd271499ab8ed7481cdec/src/server/external-services/hgnc.js#L21

**Comment by maxkfranz** [comment]
HGNC data:

```json
{
	"responseHeader": {
		"status": 0,
		"QTime": 0
	},
	"response": {
		"numFound": 1,
		"start": 0,
		"docs": [
			{
				"hgnc_id": "HGNC:5992",
				"symbol": "IL1B",
				"name": "interleukin 1 beta",
				"status": "Approved",
				"locus_type": "gene with protein product",
				"alias_symbol": [
					"IL1F2",
					"IL-1B",
					"IL1-BETA"
				],
				"location": "2q14.1",
				"date_approved_reserved": "1989-03-31T00:00:00Z",
				"date_modified": "2023-01-20T00:00:00Z",
				"date_name_changed": "2015-11-12T00:00:00Z",
				"ena": [
					"M15330"
				],
				"entrez_id": "3553",
				"mgd_id": [
					"MGI:96543"
				],
				"iuphar": "ligandId:4974",
				"pubmed_id": [
					2954882,
					2989698
				],
				"refseq_accession": [
					"NM_000576"
				],
				"gene_group": [
					"Interleukins"
				],
				"vega_id": "OTTHUMG00000131344",
				"ensembl_gene_id": "ENSG00000125538",
				"ccds_id": [
					"CCDS2102"
				],
				"locus_group": "protein-coding gene",
				"omim_id": [
					"147720"
				],
				"uniprot_ids": [
					"P01584"
				],
				"ucsc_id": "uc002tii.2",
				"rgd_id": [
					"RGD:2891"
				],
				"gene_group_id": [
					601
				],
				"location_sortable": "02q14.1",
				"agr": "HGNC:5992",
				"mane_select": [
					"ENST00000263341.7",
					"NM_000576.3"
				],
				"gencc": "HGNC:5992",
				"uuid": "4166eba3-1563-47a7-a0ed-17ac010e30af",
				"_version_": 1783704533686288384
			}
		]
	}
}

```

**Comment by chrtannus** [comment]
The **Proteins API** (EMBL-EBI) has this [endpoint](https://www.ebi.ac.uk/proteins/api/doc/#!/proteins/search), which returns a nice `FUNCTION` text--example (_TP53_):

- "Acts as a tumor suppressor in many tumor types; induces growth arrest or apoptosis depending on the physiological circumstances and cell type. Involved in cell cycle regulation as a trans-activator that acts to negatively regulate cell division by controlling a set of genes required for this process. One of the activated genes is an inhibitor of cyclin-dependent kinases. Apoptosis induction seems to be mediated either by stimulation of BAX and FAS antigen expression, or by repression of Bcl-2 expression"

However, I found it too slow (~5 seconds). Also the returned json is on the larger side (~700KB for the example bellow), if we consider we just want a couple of **id** fields and the **FUNCTION** comment.

----
Example: https://www.ebi.ac.uk/proteins/api/proteins?gene=TP53&organism=human

Returned json (partial):
```json
[
    {
        "accession": "A0A087WT22",
        "id": "A0A087WT22_HUMAN",
        "proteinExistence": "Evidence at protein level",
        "info": {
            "type": "TrEMBL",
            "created": "2014-10-29",
            "modified": "2023-11-08",
            "version": 61
        },
        "organism": {
            "taxonomy": 9606,
            "names": [
                {
                    "type": "scientific",
                    "value": "Homo sapiens"
                },
                {
                    "type": "common",
                    "value": "Human"
                }
            ],
        },
        "protein": {
            "recommendedName": {
                "fullName": {
                    "value": "Cellular tumor antigen p53",
                    "evidences": [
                        {
                            "code": "ECO:0000256",
                            "source": {
                                "name": "RuleBase",
                                "id": "RU003304",
                                "url": "https://www.uniprot.org/unirule/RU003304"
                            }
                        }
                    ]
                }
            }
        },
        "gene": [
            {
                "name": {
                    "value": "TP53",
                    "evidences": [
                        {
                            "code": "ECO:0000313",
                            "source": {
                                "name": "Ensembl",
                                "id": "ENSP00000477531.1",
                                "url": "https://www.ensembl.org/id/ENSP00000477531.1"
                            }
                        }
                    ]
                }
            }
        ],
        "comments": [
            {
                "type": "FUNCTION",
                "text": [
                    {
                        "value": "Acts as a tumor suppressor in many tumor types; induces growth arrest or apoptosis depending on the physiological circumstances and cell type. Involved in cell cycle regulation as a trans-activator that acts to negatively regulate cell division by controlling a set of genes required for this process. One of the activated genes is an inhibitor of cyclin-dependent kinases. Apoptosis induction seems to be mediated either by stimulation of BAX and FAS antigen expression, or by repression of Bcl-2 expression",
                        "evidences": [
                            {
                                "code": "ECO:0000256",
                                "source": {
                                    "name": "RuleBase",
                                    "id": "RU003304",
                                    "url": "https://www.uniprot.org/unirule/RU003304"
                                }
                            }
                        ]
                    }
                ]
            },
```

**Comment by maxkfranz** [comment]
I don't think there's a PC or GeneMANIA service for this, but it would probably be simplest to expose something in one of those systems. 

FYI: PC is only for h.sapiens

**Comment by chrtannus** [comment]
The Pathways table now gives that information.
