### ISSUE TITLE
File format clarifications

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#165]
**Description of new feature**

Make it clearer whether

- the file column names matter, and
- the sorting of the values matters.

**Motivation for new feature**

It's not clear, causing hesitation to upload.

**Comment by chrtannus** [comment]
Is this clearer now that the text about the columns format has been moved to under each _format_ section?

<img width="596" alt="upload-data-columns-doc" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/974c9694-7d0f-4c9e-b704-b75c11357601">

**Comment by maxkfranz** [comment]
One problem is that they don't know if the order of the columns matters, and the wording could be ambiguous for that.

- Yes: The order matters, because the first column must be the genes.
- No:  The order doesn't matter, because the order of the samples doesn't matter.

Other notes:

- `Exp1` isn't that clear.  Something like 'MySample1' may be better -- that shows that you can use your own column name for the samples, and it makes it clear what the column is.
- Maybe we don't need so much text.  Nobody reads anyway.  It might be simpler to just say something like, 'Make your data just like this', with the example.  Simple tooltips of a few words under two columns could give enough information, i.e.
  - Under 'Gene': Gene symbol (HGNC) or Ensembl ID
  - Under one sample column: Differential expression value (or whatever the best name to describe what this value is exactly)

**Comment by maxkfranz** [comment]
With room for more column names, you could clarify the columns a bit more too, e.g.

```
Genes | MySampleA1 | MySampleA2 | MySampleB1 | MySampleB3
```

This nudges the user to have their samples grouped in the A,B ordering we expect.

**Comment by chrtannus** [comment]
I'll work on an better image, but I still think we need some minimum specs text, because even if they don't read, that's the only documentation we have and some users may want to read more if they still don't understand the figure.
Reviewers (when we publish the paper) may need to read more info too.
Perhaps the detailed text should be in a docs page linked from here.

**Comment by maxkfranz** [comment]
That may be a good place to link to a FAQ, maybe even linking to the particular relevant questions.

We could start collecting bullet points, one per question, in #169.

People who want to read will read the FAQ.  People who don't want to read will have trouble visually focussing on the important parts of the instructions the more text there is upfront.

**Comment by maxkfranz** [comment]
@chrtannus, I've added a commit to the branch:

<img width="1006" alt="Screenshot 2023-12-12 at 14 14 06" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989043/8f37cb11-e9a8-4b8a-9354-3493d68ddcc4">

<img width="1006" alt="Screenshot 2023-12-12 at 14 14 10" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989043/d3ecc461-502e-441b-a50d-2312b2d9280a">

Notes:

- The images could be a bit taller to match the text if we want.  Not that important.
- Why are we telling users they need Ensembl or HGNC IDs?  It should just be 'gene names' and whatever they put in should just work.  Users typically have gene names IIRC, which would be HGNC -- but they wouldn't call it HGNC.  This info might be better hidden in a tooltip or something, only for advanced users.  If a typical user gets stuck and their genes aren't recognised, they aren't going to map them for us, they're going to give up.  So it's probably best to hide the Ensembl/HGNC bit (and show it only for advanced users), and if users have trouble with gene recognition, then we should consider having better builtin mapping.

**Comment by chrtannus** [comment]
@maxkfranz, Looks good! I'll play with the layout and tables to see if it makes sense to make them taller (e.g. increase the padding, add more rows).

@mikekucera, I think you have suggested the addition of "Ensembl or HGNC IDs". What do you think of moving it from the text to a tooltip and FAQ?

**Comment by mikekucera** [comment]
> @mikekucera, I think you have suggested the addition of "Ensembl or HGNC IDs". What do you think of moving it from the text to a tooltip and FAQ?

I'm fine with that. If the user submits a file with unmappable IDs then we should have an appropriate error message explaining why their file didn't work. Right now it probably just gives a generic error about bad format, or that the resulting network is empty.

**Comment by maxkfranz** [comment]
> @maxkfranz, Looks good! I'll play with the layout and tables to see if it makes sense to make them taller (e.g. increase the padding, add more rows).

@chrtannus, another option that may be a bit simpler is to make the the last paragraph, about the header and data rows, fine print (`<small>` or similar).  It's not as important, so it doesn't have to be as big as the other text.

> I'm fine with that. If the user submits a file with unmappable IDs then we should have an appropriate error message explaining why their file didn't work. Right now it probably just gives a generic error about bad format, or that the resulting network is empty.

Great idea to put the info in the error message.  It's more actionable there.

**Comment by maxkfranz** [comment]
Nice
