### ISSUE TITLE
Group A and Group B aren't clear

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#166]
**Description of new feature**

Make it clear which is Group A and which is Group B.

We've got to either name the buttons better or include a little bit of text under 'Group A' and 'Group B' to clarify.

**Motivation for new feature**

Nobody reads the text above, but people look at the buttons.

**Comment by mikekucera** [comment]
Perhaps a confirmation screen as the last step of the wizard?

**Comment by maxkfranz** [comment]
> Perhaps a confirmation screen as the last step of the wizard?

We might need both better labels and a confirmation screen.

Maybe even some steps in the wizard should be split up.  The file type previews are a lot all at once, for instance and people don't read everything.  Ideally, each step would be small and just one thing -- but we don't want too many steps either.

**Comment by maxkfranz** [comment]
Related: If I mess up the buttons (i.e. A is B and B is A), make it easy to swap them.

**Comment by maxkfranz** [comment]
Labels are now: experiment and control

Closing

**Comment by mikekucera** [comment]
I don't think this is fully fixed on mobile. The labels collapse down to A/B icons. Christian said he would change them to E/C icons.
<img width="501" alt="Screenshot 2023-11-09 at 9 47 34 AM" src="https://github.com/cytoscape/enrichment-map-webapp/assets/5350528/320e5dc1-92e7-48e9-9460-a33249d3caf0">

**Comment by maxkfranz** [comment]
Good catch

**Comment by chrtannus** [comment]
Mobile icons changed to E/C:
<img width="428" alt="e-c-icons" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/5230b4eb-bcdc-4745-8aae-5e496061b3fa">
