### ISSUE TITLE
Tooltip for intersection icon should be on the entire line

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#168]
**Description of new feature**

- The tooltip target for the intersection icon should be on the entire line, rather than just the icon.
- It's currently only on the icon itself, so it's hard to find.

**Motivation for new feature**

- People try to hover over the word 'genes' and get nothing.
- #164

**Comment by chrtannus** [comment]
Done! The tooltip now appears when hovering the "_Genes (`{total}`)_" title as well, not just the icon:
<img width="336" alt="genes-tooltip" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/5492f174-eb7b-4bbe-a111-ba4a4c5aac70">
