### ISSUE TITLE
Page zooming should be disabled

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#174]
**Description of new feature**

The user should not be able to accidentally zoom the page.  When they zoom the page (not the network), they get lost.

It's fine to allow `CMD+` to adjust the font size, but not to zoom the page.

**Motivation for new feature**

Users accidentally do it, and it's really annoying.

**Comment by maxkfranz** [comment]
This isn't completely related to this issue, but I want to log this somewhere re. iPad: https://bugs.webkit.org/show_bug.cgi?id=210071

**Comment by chrtannus** [comment]
I think CMD+ to zoom the whole thing is the standard and I use often, so the standard should be used. Increasing the font size only could be very messy. You have to increate the panels, too.

**Comment by maxkfranz** [comment]
There are two different 'zoom' operations that the browser allows:

1. `CMD+`: This doesn't really 'zoom', but it changes the relative DPI of the page as reported by some parts of the browser's APIs, like the font size.
2. Actual zooming.  Think iPad pinch to zoom, where you really zoom into a particular part of the page.

(1) is fine to allow.  (2) should be forbidden in an app.
