### ISSUE TITLE
Gene -> Pathways overview

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#178]
**Description of new feature**

It's difficult to get an overview of what pathways in the figure are associated with a gene. 

When hovering over a gene in the sidebar, it would be nice to highlight the associated pathways in the figure.

**Motivation for new feature**

A highlight gives an overview.  Seeing the list in the sidebar is nice for when you want to find a particular one and click it, but it doesn't really give an overview -- where the edges are important.

**Comment by chrtannus** [comment]
Done:
<img width="1190" alt="node-highlight" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/34833456-3582-4446-8301-d0a1ab305913">
