### ISSUE TITLE
Gene set display

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#18]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

Show information about a gene set.

- When a user clicks on a gene set (i.e. a child node), update the sidebar to show information about the gene set (name, description, etc.).
- Show the genes in the set
- Hide the gene search bar in this state.  Show something like '< Back to all genes' in its place so the user can reset the sidebar to show all genes and the search box.

Depends on:

- #16
- #20 (for score bar styling coordination etc.)

**Motivation for new feature**

_Describe your use case for this new feature._

Users want contextual information about gene sets

**Comment by mikekucera** [comment]
This is partially working already. I created an endpoint that returns the contents of the gene set along with ranks. I had to "join" the gene set database document with the ranked-gene-list document in mongo.

I believe we decided to not support multi-select for the MVP, right?

**Comment by maxkfranz** [comment]
> I believe we decided to not support multi-select for the MVP, right?

No selection at all, I think (i.e. disable selection state mutation).  Just click.  That way, the user can never activate more than one element at once for info display
