### ISSUE TITLE
Expanding/Collapsing of clusters

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#184]
**Description of new feature**

Note: This feature is experimental. It adds complexity to the app and to the figure so we may decide its not worth it to implement.

Currently we show the fully collapsed "summary network", where some nodes actually represent collapsed clusters. This feature would be to allow the user to see which nodes are actually collapsed clusters, and allow them to be expanded so that the individual pathways within a cluster become visible.

**Motivation for new feature**

Potential benefits...
- Allows the user to see the individual pathways within a cluster. (Not sure if this will make the network easier to understand, since the ambiguity between pathway/cluster is removed, or less clear because there are more visual artifacts to parse.)
- Might work more synergistically with the data table.
  - For example if the user selects a pathway, we could zoom in on the cluster, expand it, then select the individual pathway.
- Figure is more similar to figures created by EM-desktop.
- Facilitates exploratory analysis (maybe).

**Comment by mikekucera** [comment]
Ideas to explore...

bubble-sets extension: 
- http://www-ui.is.s.u-tokyo.ac.jp/~takeo/research/bubble/index.html
- https://github.com/upsetjs/cytoscape.js-bubblesets

expand-collapse extension:
- http://ivis-at-bilkent.github.io/cytoscape.js-expand-collapse/demo/demo.html

**Comment by mikekucera** [comment]
The expand-collapse extension was rather unreliable, and does not work well with the auto-zooming that we currently use.

**Comment by mikekucera** [comment]
From Max...

> Some thoughts if we go forward with the bubble approach:
>
> The discrete layouts support a spacingFactor, which you can use to stretch or squish a layout.
>
> It doesn’t look like it’s documented, but the preset layout probably also supports spacingFactor.  If not, it could be added easily.
> 
> Then the preset layout could be used to squish a cluster to collapse, and similarly to stretch a collapsed cluster to expand it back to normal — just like in the bubble clusters paper.  You could even use an animation, since the layouts already support that.
>
> Re. compound-like behaviour: You could add compound parent nodes to each cluster to make them all draggable as a unit, with something like background-opacity:0.001 to make the compound parent itself not distracting (i.e. you’d just see the bubble).  Even if the compound would be made non-interactive — since the bubbles might overlap, making interactivity difficult — you could still use it to create a label around the bubble.

**Comment by mikekucera** [comment]
I experimented with using bubblesets and compound nodes together. See the below video.

- The compound node is used to provide the label to attach to the cluster, and allows the cluster to be dragged as a whole.
- Bubblesets is used to draw the cluster bubble.
- I changed the style a bit so that the node labels look similar to the cluster labels.

https://github.com/cytoscape/enrichment-map-webapp/assets/5350528/5ab2381d-b1d5-4a3a-8808-1576dc92b26b

**Comment by mikekucera** [comment]
> It seems like there was a bit of stutter when zooming. Did that happen on your device normally, or is it just a side effect of the recording?

That always happens for me when I zoom with the mouse wheel. Zooming with two fingers on the trackpad is smooth.

> Did you use the spacing factor with the preset layout? If so, I'll add a ticket so we can get that officially documented in the upcoming version.

Yes I did.

**Comment by maxkfranz** [comment]
> That always happens for me when I zoom with the mouse wheel. Zooming with two fingers on the trackpad is smooth.

OK.  That's a hardware/browser issue.  The mouse wheel for that mouse isn't reporting fine-grained scroll values like the builtin Mac trackpad does.  Sometimes installing the mouse driver software can help, and sometimes it makes things worse.  It's a crapshoot.

> Yes I did.

See https://github.com/cytoscape/cytoscape.js/issues/3172
