### ISSUE TITLE
The pathway panel should be responsive

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#187]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

The panel should be responsive.  It should not overtake all the screen if you have something like a Macbook-Air-sized screen.

**Motivation for new feature**

_Describe your use case for this new feature._

It overtakes the whole screen:

<img width="1132" alt="Screenshot 2023-10-05 at 09 22 57" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989043/fc5e47c1-cf75-47b9-acbf-2664d64df670">

**Comment by chrtannus** [comment]
This is how it looks on different screen sizes when the expanded table takes 1/3 of the content area's height (excluding the height of the app header):

- **iPhone 12 PRO Max:**
  
  <img width="433" alt="iPhone12_ProMax" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/5b180aba-2235-4259-97c6-3ed8edb1b1ce">

- **MacBook Air:**
  
  <img width="997" alt="MacBook_Air" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/9694b40b-537d-40d1-b7d1-f3d88777d954">

- **UDH (3840×2160):**
  
  <img width="994" alt="UHD_3840×2160" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/686eafd3-0f88-4730-a2ea-ad980d899a39">

**Comment by maxkfranz** [comment]
Looks good to meOn Nov 15, 2023, at 10:55, Christian Lopes ***@***.***> wrote:﻿
This is how it looks on different screen sizes when the expanded table takes 1/3 of the content area's height (excluding the height of the app header):


iPhone 12 PRO Max:



MacBook Air:



UDH (3840×2160):
