### ISSUE TITLE
performance issue expanding large cluster

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#192]
**Describe the bug**

Expanding a large cluster (~90 nodes) causes the UI to hang for a few seconds.

**To Reproduce**

- Create a network from the GSE129943_rsem_counts_HGNC
- Find the cluster named "apc degradation securin" (it contains the pathway named "gli3 is processed to gli3r by the proteasome")
   - This cluster contains 93 nodes and 3844 internal edges.
- Expand the cluster

- This causes the UI to freeze for about 10 seconds.
- The expanded cluster is also quite unresponsive, trying to drag it around also creates UI hiccups
- Note that when the cluster is collapsed the performance of dragging it around is much better

**Expected behavior**

- It should expand and animate just like the smaller clusters do.

**Additional context**
- Try setting the bubble set "throttle" parameter back to the default.
- Maybe it has something to do with labels, or number of edges. When the cluster is collapsed the 3844 edges are hidden, that might be helping performance.

**Comment by maxkfranz** [comment]
Is the animation applied before or after the edges are shown?

Showing the edges only after the animation has completed may help, if we're not doing that already.

**Comment by maxkfranz** [comment]
Also, if the cluster is basically K_90, then we it could be that we may as well not show the intra-cluster edges at all.

**Comment by mikekucera** [comment]
Results of some experimenting...
- Setting "visibility:hidden" on edges doesn't help performance very much. Removing the edges helps a lot.
- The bubble sets throttle parameter has no effect on performance.
- Setting animate:false when expanding/collapsing helps a bit.

Here is a video where the animation is disabled and all cluster internal edges are removed. The performance is pretty good. However, as shown in the video, removing all the edges then dragging a node away from its cluster can mess up the bubble path. Could we automatically add back the edges if a node is dragged too far away from a cluster? Any other ideas?


https://github.com/cytoscape/enrichment-map-webapp/assets/5350528/98b638ea-a7d3-4f37-a2f7-9188b09ca8ad

**Comment by maxkfranz** [comment]
> Setting "visibility:hidden" on edges doesn't help performance very much. Removing the edges helps a lot.

This may be the difference between rendering performance and just iteration performance.  We'd have to profile to be sure, in any case.

> Could we automatically add back the edges if a node is dragged too far away from a cluster? 

I suppose you could add back the edges for grabbed nodes when they're grabbed.  If users just drag a few at once, it's probably not many.

A more restrictive/performant set of edges may be the edges between the set of grabbed nodes and the other, non-grabbed nodes in the cluster.  That way, if you grab an entire cluster, you don't add any edges.  The worst case would be grabbing half the nodes in the cluster, but at least it wouldn't be all of them.

Another enhancement on the previous idea would be to set a max for the number of temporary edges.  You might not need all the edges between the grabbed set and the ungrabbed set.  Just a small, random sample might suffice.

**Comment by mikekucera** [comment]
> This may be the difference between rendering performance and just iteration performance (i.e. expensive iterations, like recalculating bubbles). We'd have to profile to be sure, in any case.

It may be the bubble path, it still considers hidden edges when creating the path.
