### ISSUE TITLE
On-screen legend

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#21]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

Include an on-screen legend for the network figure.

- The legend should be on the bottom corner of the screen, probably bottom-right.
- The legend should show all meaningful mappings in the stylesheet.

Depends on:
-  #20 

**Motivation for new feature**

_Describe your use case for this new feature._

Help the user understand the figure.

**Comment by mikekucera** [comment]
This manual page describes the style of EM Desktop networks...
https://enrichmentmap.readthedocs.io/en/latest/Network.html

We need to relay the same information to the user with just the legend. Perhaps tooltips will be needed.

**Comment by maxkfranz** [comment]
> Could the legend be implemented as a small cytoscape.js network on a separate canvas? There may be some advantages that I can think of….
> 
> 1. Can use the same stylesheet as the main network. If we make a change to the stylesheet it will automatically update the legend as well.
> 2. We can use the cy.js API for legend image export. It will work exactly the same way as the network image export.

This depends on what we decide for the network style (#20) and whether we can represent each legend entry as one or more elements.

**Comment by maxkfranz** [comment]
> An approach for the legend:
> 
> * Render the legend as SVG in the DOM.
>   
>   * Use the embedded font in the app, Open Sans, to guarantee the font rendering is consistent.  That should make everything more or less pixel-perfect, which makes programmatically generating an SVG much easier.
>   * TBD:  This might not be able to use the React render method, because we'd need the SVG rendering code to be reusable.
> * For export: Reuse the legend-to-SVG code to draw the SVG on a 2D canvas.
>   
>   * The canvas should be off of the screen, either with OffscreenCanvas or an ordinary Canvas that's positioned off-screen.
>   * Save the canvas content as a PNG, either using a [blob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) or a [data URL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL).
> * For future:  The SVG generation code and canvas export code can be reused in future if/when we support automatically composing the legend into a single figure image export.
>   
>   * Sources: Cy PNG, legend canvas, output canvas (the merged one for export)
>   * Onto to output canvas, [draw](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) the Cy PNG, then [draw](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) the legend scaled in the corner.

Ref: #22

**Comment by mikekucera** [comment]
I'm using cy.js to create the legend as I mentioned in a previous comment.
