### ISSUE TITLE
Minimal figure export (MVP)

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#22]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

Allow image export of the figure.

- Export two images: the network, the legend
- The images should both be high-res.
- The user can combine these two high-res images and resize them so that they'll work well in their paper.

Depends on:

- #20 
- #21
- #15

**Motivation for new feature**

_Describe your use case for this new feature._

The user needs to include the figure in their paper.

**Comment by mikekucera** [comment]
This is partially working already. The code taken from CE includes a "share" button that allows the network to be exported as a PNG or JPEG. The cytoscape.js API is used for this.

**Comment by maxkfranz** [comment]
> This is partially working already. The code taken from CE includes a "share" button that allows the network to be exported as a PNG or JPEG. The cytoscape.js API is used for this.

It looks like we'd just need the high-quality option from the old feature for now

**Comment by maxkfranz** [comment]
An approach for the legend:

- Render the legend as SVG in the DOM.
  - Use the embedded font in the app, Open Sans, to guarantee the font rendering is consistent.  That should make everything more or less pixel-perfect, which makes programmatically generating an SVG much easier.
  - TBD:  This might not be able to use the React render method, because we'd need the SVG rendering code to be reusable.
- For export: Reuse the legend-to-SVG code to draw the SVG on a 2D canvas.
  - The canvas should be off of the screen, either with OffscreenCanvas or an ordinary Canvas that's positioned off-screen.
  - Save the canvas content as a PNG, either using a [blob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) or a [data URL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL).
- The SVG generation code and canvas export code can be reused in future if/when we support automatically composing the legend into a single figure image export.
  - Sources: Cy PNG, legend canvas, output canvas (the merged one for export)
  - Onto to output canvas, [draw](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) the Cy PNG, then [draw](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) the legend scaled in the corner.

**Comment by mikekucera** [comment]
I'm already almost done using cy.js for the legend.

**Comment by maxkfranz** [comment]
Great.  The 'for future' point still stands for later composition if/when we do that in a future milestone.
