### ISSUE TITLE
Hover effect on genes gets stuck

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#221]
**Describe the bug**
_A clear and concise description of what the bug is._

Sometimes, the hover effect persists even after you mouseout the gene name.

**To Reproduce**
1. Go to a result.
2. Play with the hover effect.  Not sure exactly how to reproduce this.
3. Sometimes, the hover effect persists even though you've moved the cursor over the network.

**Expected behavior**
_A clear and concise description of what you expected to happen._

- The hover effect should be cleared whenever you mouseover the network.
- The hover effect should be cleared whenever you mouseout the genes panel overall.
- Maybe: There could be a debounce/throttle/delay race condition on slow machines.

**Comment by chrtannus** [comment]
When tapping on mobile/tablets, it should now select and expand the gene instead of just doing the same as hovering on desktop.
