### ISSUE TITLE
Slow wifi kills the genes side bar

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#222]
**Describe the bug**
_A clear and concise description of what the bug is._

When the wifi is slow, the genes sidebar is slow.  This seems to slow down the entire page.  You get a page with the overall layout, but all the content (side bar list, network, etc.) are all empty for a long time.

- Slow to load initially
- Slow to load descriptions when you click

**To Reproduce**
1. Simulate poor wifi with the Network Link Conditioner: https://apple.stackexchange.com/questions/24066/how-to-simulate-slow-internet-connections-on-the-mac
2. Load a result, ideally the sample file with all genes in it
3. Click the genes

**Expected behavior**
_A clear and concise description of what you expected to happen._

- Ideally, it should feel instant, especially for the clicking case.
- If initial loading is always going to be slow for large files, then we should show a spinner.

**Comment by mikekucera** [comment]
We already load all the gene info into minisearch. We should just store the node-to-gene mapping on the client which will remove the need to query the server for gene info every time the selection changes.

**Comment by maxkfranz** [comment]
Sounds good
