### ISSUE TITLE
Unclear loading feedback on result screen

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#226]
**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**
1. Go on slow wifi or simulate it.
2. Click the example/demo result.
3. The page kind of loads, but everything is empty.
4. The network loads in.
5. The genes panel and the pathways panel load in.
6. During (3), (4), and (5), it's not clear that the result is loading.  It just looks empty.  Is something broken?  Did it glitch out?  Should I hit the refresh button?

**Expected behavior**
_A clear and concise description of what you expected to happen._

There should be some kind of feedback that it's loading, like a spinner.

**Tested on iPad using lousy wifi on an airplane.

**Additional context**
_Add any other context about the problem here._

**Comment by princyym** [comment]
Hello, I am eager to work on this issue could you please assign me this issue. actually, i am actually a beginner and try to contribute related to the webpage issues.

**Comment by maxkfranz** [comment]
@chrtannus, I've added the bundle viz to the `fix/slim-bundle` branch.  It should help you slim down the dependencies:

<img width="1279" alt="Screenshot 2024-02-14 at 12 43 23" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989043/ab50df9b-df04-4028-8ce6-26a195fb2160">

```
npm run bundle-profile
```

**Comment by chrtannus** [comment]
I just added this to the center of the static HTML page:

![em-loading](https://github.com/cytoscape/enrichment-map-webapp/assets/989686/9cae6806-ddbe-4311-85a4-42f55672ee84)
This is just a gif from a cropped screen capture, not the whole page.

This is how it should look on **MacBook Air** and **iPhone 13 PRO**:

<img width="75%" alt="MacBookAir" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/3739ab54-0620-4e02-94ca-28f290da6695">
<img width="25%" alt="iPhone13PRO" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/87dea5b9-9706-4d96-a84d-85e0302b1723">
