### ISSUE TITLE
Gene List: gene with rank 0.0 error

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#230]
- Open the demo network.
- Search for the gene 'FAM117B'
  - This gene has a rank of exactly 0.0
- There is an error in the console (see screenshot).

I tracked it down as far as the UpDownHBar component. Passing 0.0 for the 'value' property to this component produces the error. Passing a value very close to zero (eg 0.0000001) instead of zero avoids the error, but I'm not sure if that's the best fix.

<img width="1079" alt="Screenshot 2024-01-22 at 2 31 37 PM" src="https://github.com/cytoscape/enrichment-map-webapp/assets/5350528/e91129fc-86cd-4dce-b689-8da3619a31a7">

**Comment by mikekucera** [comment]
I also fixed a bug where genes with zero rank were getting filtered out from the sidebar. Its not safe to do `if(gene.rank)` to test for genes with ranks, its better to use lodash `_.has(gene, 'rank')`

**Comment by maxkfranz** [comment]
Closing as #231 is merged

**Comment by mikekucera** [comment]
This is a separate bug.

**Comment by maxkfranz** [comment]
OK

**Comment by chrtannus** [comment]
This is a separate issue,  but one side effect of rounding the rank value for the chart label is that the label "0.00" can be aligned to the left or right, depending on the actual value (e.g. 0.0001 vs. -0.0001):
<img width="301" alt="rounded-zeros" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/e591154b-10cb-4dd4-aad2-2e45fc6c3ee4">

This can be seen both as a minor issue ("0.00" values not aligned) or as a feature (it indicates the actual value is positive or negative).

**Comment by chrtannus** [comment]
I've just modified it to pass the rounded values to the Horizontal Bar component, so all '0.00' labels are aligned the same way (centered):
<img width="319" alt="all-centered" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/0780b098-66d9-4f3f-b9ae-02be9be9e6be">

See comit [a01064d](https://github.com/cytoscape/enrichment-map-webapp/commit/a01064d536e8c1e0072e31db49c6a281cbc342cc).
