### ISSUE TITLE
Mouse cursor for "view demo network" link should be a hand

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#238]
**Describe the bug**

The mouse cursor when hovering over the "view demo network" link is a text-select cursor. It should be a hand.

This happens in Chrome and Safari, haven't tried other browsers.

<img width="990" alt="Screenshot 2024-01-31 at 5 41 38 PM" src="https://github.com/cytoscape/enrichment-map-webapp/assets/5350528/2f1b4bff-b477-4351-9118-9397e8dd0988">

**Comment by chrtannus** [comment]
Instead of adding `cursor: pointer` as a `style` (or MUI class) to every single <Link> component that has no `href` attribute, I just added this to the _base.css_ file:
```
a {
  cursor: pointer;
}
```
I can't think of a scenario (in this app, at least) where a link shouldn't have a pointer cursor.
