### ISSUE TITLE
The demo network doesn't have an associated paper indicated

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#245]
**Describe the bug**
_A clear and concise description of what the bug is._

As a prospective user of the app, if I want to view the demo network, I need to know what paper it's from so I can make sense of it.  Otherwise, it's just a random network.

The demo is great, but there's not much context.  The paper would clear things up.

**To Reproduce**
1. Go to the home page
2. Notice the 'demo network' link, by the button
3. There's no link to Pubmed
4. When I click to get the demo, there's no Pubmed link on the result page either.  It might be good to have it there too, in case the user clicks the demo quickly without reading too much.

**Expected behavior**
_A clear and concise description of what you expected to happen._

A prospective user would want to see the Pubmed link for the paper if they view the demo network.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

<img width="805" alt="Screenshot 2024-02-21 at 14 13 37" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989043/7f95c544-224b-43a0-95a8-e9d6e035b4f8">

**Comment by mikekucera** [comment]
Perhaps use the data from the pathway commons tutorial, and link to the tutorial...
https://www.pathwaycommons.org/guide/workflows/rna_seq_to_enrichment_map/

**Comment by mikekucera** [comment]
Good news, the demo network already the one from the pathway commons tutorial: `brca_hd_tep_ranks.rnk`. We just need to add a link to the tutorial somewhere.

**Comment by maxkfranz** [comment]
Great

**Comment by chrtannus** [comment]
Updated demo dialog:

<img width="446" alt="updated-demo-dialog" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/10eb2f48-3529-455c-afd6-6869a1d9643c">
