### ISSUE TITLE
The genes panel formatting gets really messed up on some Windows computers

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#251]
**Describe the bug**
_A clear and concise description of what the bug is._

The formatting of the genes sidebar gets really messed up on some Windows computers.  

- I don't know how to reproduce this issue yet.
- Basically, the bar UI overflows into the next line.
- Maybe it's related to font rendering?
- This could probably be forced to be reproduced by editing the CSS for the bars so that the overflow on Mac too by making them bigger.  Then the style should be set so that the bars don't overflow to the next line, even if they're too big. 

**To Reproduce**

TBD.

It happens on some Windows computers and not others.  Which browser is used doesn't matter.  Same on Chrome or Edge.

**Expected behavior**
_A clear and concise description of what you expected to happen._

It should work on Windows.

**Screenshots**

I'll include a screenshot the next time I see this.

**Comment by mikekucera** [comment]
This may already be fixed. I noticed something like this and Christian fixed it.
https://github.com/cytoscape/enrichment-map-webapp/commit/e5837d0c1eaf48942288d9c74694ee335d5fe8e5

**Comment by chrtannus** [comment]
Please try again on Windows (Chrome and Edge at least). This is probably fixed.

**Comment by maxkfranz** [comment]
I've sent an email
