### ISSUE TITLE
Ensembl IDs with a version number break file upload

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#252]
**Describe the bug**
_A clear and concise description of what the bug is._

If you upload a file with Ensembl IDs that have a version number in them, then the upload fails.

It took forever to figure out why this was happening.  There was no feedback in the UI for what was wrong, or which rows in the spreadsheet were problematic so it was a lot of guess work.

Users would have given up and left the site if I weren't there to help them.

**To Reproduce**
1. Go to enrichmentmap.org
2. Click on 'Get started'
3. Upload a file with Ensembl version numbers in the IDs, like `ENSG00000139618.18` for `ENSG00000139618` -- BRCA2

**Expected behavior**
The version number shouldn't make a difference to the ID.

`ENSG00000139618.18` is the same as `ENSG00000139618`.

**Comment by maxkfranz** [comment]
See also: https://useast.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000139618;r=13:32315086-32400268

**Comment by mikekucera** [comment]
I think we need to warn the user about ids that can't be mapped. As an example, the sample data file `GSE129943_rsem_counts...` contains 21382 invalid IDs out of 57905 rows. Basically 37% of the IDs can't be mapped but we build the network anyway and never tell the user. 

To be fair that file has both 'Ensembl' and 'HGNC' columns, and many of the cells in the 'HGNC' column are empty or have 'NA' for the value. (I didn't check if these are the same rows as the ensembl IDs that can't be mapped). So its probably fine to create the network from this file, but I still think the user needs to be informed in some way. 

I suggest we show a non-intrusive pop-up after the network is created with a simple warning.
