### ISSUE TITLE
The PNG export is not high-res

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#255]
**Describe the bug**
_A clear and concise description of what the bug is._

The PNG export is not high-res.  It's blurry.

**To Reproduce**
1. Go to enrichmentmap.org
2. Go to the demo
3. Download the images
4. Open the PNG
5. Zoom in even just a little bit
6. It's blurry

**Expected behavior**
_A clear and concise description of what you expected to happen._

It should be higher res.

**Comment by mikekucera** [comment]
The large image is much larger now. We also have PDF export working.
