### ISSUE TITLE
Clicking in the pathways panel loses your place when you searched

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#257]
**Describe the bug**
_A clear and concise description of what the bug is._

If you made a search and then you just want to see something in the search, you click the pathway.  Now, everything gets reset and you lose your place.  Where did it go?  It's gone.

**To Reproduce**
1. Go to enrichmentmap.org
2. Go to the demo
3. Type "signalling" in the search
4. Click on "integrin signalling pathway"
5. The search is gone.  The pathway is gone.  Where did everything go?

**Expected behavior**

The panel shouldn't jump around and reset randomly.

**Screenshots**

https://github.com/cytoscape/enrichment-map-webapp/assets/989043/8fc404c2-1e95-4334-b5c1-c5cffce1222b

**Comment by mikekucera** [comment]
looks good
