### ISSUE TITLE
Auto-hiding of labels is too aggressive

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#258]
**Describe the bug**
_A clear and concise description of what the bug is._

There are medium zoom levels where you want to see the labels and you can't, especially if you have a Windows computer that doesn't do smooth zooming/scrolling and doesn't have a high-DPI screen.

Secondly, the users expect the image export to look exactly like what's on screen.  If we hide labels conditionally based on zoom, then the image export doesn't look the same.  Users are hesitant to export, because the "figure labels are broken".

**To Reproduce**
1. Go to enrichmentmap.org on a Windows computer with an HD screen -- not high-DPI like a Mac, not 4K
2. Click on the demo
3. Zoom in a bit
4. You still can't see the labels

**Expected behavior**
_A clear and concise description of what you expected to happen._

You should be able to see the labels all the time.  Hiding the bubble children labels is fine, because you don't want to see them and they're not shown in the image export.

**Comment by mikekucera** [comment]
Auto hide appears to be disabled.
