### ISSUE TITLE
Partitioned layout

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#263]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

The layout should have three partitions:

1. Blue
2. Mixed blue and red
3. Red

Within each partition, each component can be laid out with either a FD layout or just a circle layout (or grid for singletons):

- Singletons (disconnected nodes): All in a grid at the bottom of the partition, similar to now
- The components with no clusters/bubbles should be circle
- The components with bubbles should be FD

Each of the above is just a separate layout call on each component, i.e.:

```js
cy.components().forEach(component => component.layout(options).run());
```

There's a packing algorithm in the builtin COSE layout that we can just copy, or we can make it public API in the library, e.g. `elements.pack()`.  Or we can use the COSE packing from Bilkent (Ugur's group).

Image of layout:

<img width="777" alt="em-ideal-layout-example" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989043/615e11d7-b17a-40e5-a872-95541fc88039">

**Motivation for new feature**

_Describe your use case for this new feature._

The current layout isn't so great, and people complain.  It's hard to drag select parts of the network, because you select more than you intended.

**Comment by mikekucera** [comment]
The packComponents() function from cytoscape-layout-utils doesn't put components in the order we want. 
The built-in cose layout doesn't layout the clusters in the way we want. 

I'll try using 'fcose' as it is now so that the clusters are laid out better, then I'll try the packing algorithm from the built in cose. If that doesn't work...

**Comment by maxkfranz** [comment]
The packing algorithm from COSE would probably need to be copy-pasted out for now, if we don't start by making in generic:

https://github.com/cytoscape/cytoscape.js/blob/unstable/src/extensions/layout/cose.js#L1263-L1337

**Comment by mikekucera** [comment]
Hey Max, do you know if this is a typo or intended? (the width and height being swapped)
https://github.com/cytoscape/cytoscape.js/blob/unstable/src/extensions/layout/cose.js#L329-L330

**Comment by maxkfranz** [comment]
> Hey Max, do you know if this is a typo or intended? (the width and height being swapped) https://github.com/cytoscape/cytoscape.js/blob/unstable/src/extensions/layout/cose.js#L329-L330

Looks like a typo

**Comment by chrtannus** [comment]
It looks good to me!
