### ISSUE TITLE
Selecting multiple nodes can get the UP/DOWN sorting wrong

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#268]
**To Reproduce**
1. Go to the example query
2. Select a red node
3. Clear the selection
4. Select a group of blue nodes
5. The sorting is still UP

**Expected behavior**

The sorting should be the same as the colour of the selection (one or more nodes), but only if all the nodes in the selection are the same colour.

**Comment by chrtannus** [comment]
This should be fixed now.
