### ISSUE TITLE
Revised instructions for file upload

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#269]
**Description of new feature**

- [x] Use a bigger figure
- [x] 4 samples for the raw counts
- [x] Convert text into arrows
- [x] Call the columns Sample instead of Exp
- [x] Need to mention Ensembl in one of the arrows (gene name or Ensembl)
- [x] Good to use the words "raw counts" to describe the file?
- [x] Remove : Other columns: must be marked as “ignored” in the next step.
- [x] Copy some ideas from GSEA examples: e.g. negative values for rank
- [x] When you select expression or preranked, that tells the file upload what type you have
- [x] The accordion should have a radio icon beside each, indicating which is selected

https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/File:Rnk_format_snapshot.gif

**Motivation for new feature**

- People don't read.
- People make mistakes in upload.

**Comment by chrtannus** [comment]
New UI so far:

<img width="533" alt="rnaseq" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/903cead3-7f53-46c3-8ab7-11d4324bc92b">

<img width="533" alt="ranked" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/7d7cdc8d-450e-41c7-b63a-d625f783a3e2">

**Comment by chrtannus** [comment]
Latest screenshots:

<img width="539" alt="upload1" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/f692fa01-ac28-4cab-9d8b-57805ea5cd3a">
<img width="539" alt="upload2" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/7d3f65d3-9040-430e-86a4-7e0767a35c00">
