### ISSUE TITLE
Disable text selection

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#271]
**Describe the bug**
_A clear and concise description of what the bug is._

People try to drag select or shift click to select multiple things in a table.

**Expected behavior**
_A clear and concise description of what you expected to happen._

If we don't support multiple selection, you shouldn't see anything change.

Disable the text selection outside of text boxes.

**Comment by chrtannus** [comment]
Duplicate of #158.
