### ISSUE TITLE
Pre-validation + UI feedback for upload

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#272]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

- [x] Detect common issues with upload
  - [x] Bad row (e.g. missing name)
  - [ ] ...
- [x] Give feedback in the UI for the user to fix the file
  - [x] Row numbers for bad rows
  - [x] Nothing is signifcant
  - [ ] Even better: preview of a failing row (or all failing rows), one example per problem  

**Motivation for new feature**

_Describe your use case for this new feature._

**Comment by chrtannus** [comment]
I made a few changes to the UI, specially to the column selectors:

<img width="424" alt="ranks-ui" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/67ea162e-ef0a-4a3d-8267-db3205118cf2">
<img width="599" alt="expressions-ui" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/8848bcf2-f67b-4adc-96f8-dec2377592af">
