### ISSUE TITLE
Add README file to the download zip

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#277]
**Description of new feature**

Add a README file to the download zip.

The file could contain the following information:
- The permalink for the network.
- How to cite EnrichmentMap
- Links to other resources like a FAQ.
- A quick description of each file in the zip.
- Instructions on how to load the data into EM-desktop.
- The filter (cutoff) parameters used by the EM-service. (More advanced users ask to see this. Its also useful when loading into EM-desktop.)
- Any warnings from the import step. For example if X number of ensembl genes could not be mapped we could say that.
- Other useful information...

**Comment by chrtannus** [comment]
It looks good--sample:
[README.md](https://github.com/cytoscape/enrichment-map-webapp/files/14875101/README.md)
