### ISSUE TITLE
Color nodes by q-value (padj)

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#28]
**Description of new feature**

The network style should use a color gradient on the q-value (ie the node's 'padj' attribute (that's what FGSEA calls its q-value)).

The range should be 0 to max q-value.

The legend should show the user the range of q-values used in the style.

Note, we can't specify the max q-value like you would normally do when specifying filter parameters because I added the ability to limit the number of nodes  returned by the EM service. We need to find what the actual largest q-value in the set of returned nodes is. This could be done by the EM service, the node service, on the client, whatever makes the most sense for the use case.

**Motivation for new feature**

Color is normally part of the EM network style.

See also:

- #20

**Comment by maxkfranz** [comment]
How about green as the colour?  People intuit green as good, and 'good' q-values or p-values are low.  'Better' q-values would be a stronger shade of green.

Aside:  We could grey out nodes if they have a value beyond a cut-off (e.g. a p-value above 0.05 is generally considered 'bad').  That would be something like green (0) to grey (0.05) to light grey (max).  Though hopefully, we're not showing any of those sorts of nodes to begin with (i.e. all nodes should be relatively 'good', only shades of green).
