### ISSUE TITLE
Title Editor broken on Android

### ISSUE THREAD

**Issue by chrtannus** [cytoscape/enrichment-map-webapp#293]
Cannot select the network title and edit it on Android devices, it keeps losing focus.

![bug-title-editor-android](https://github.com/cytoscape/enrichment-map-webapp/assets/989686/ac619edc-0800-40cc-926e-794eed8aff56)

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser Chrome

**Comment by chrtannus** [comment]
Pressing ESCAPE to cancel (desktop) does not work either.

**Comment by chrtannus** [comment]
@mikekucera, could please review this?

- Press ENTER or just blur to apply the changes (refreshing the page or going to home should show the new network name).
- If the title field is empty (or has only space characters), trying to apply the changes should just rollback/cancel it.
- Pressing ESCAPE should rollback any changes (i.e. show previous network name) and blur.
- It should work on iOS and Android.

**Comment by mikekucera** [comment]
It works on desktop (chrome) and ios (safari). I don't have an android device to test with, sorry.
