### ISSUE TITLE
Cannot go back to Home on mobile

### ISSUE THREAD

**Issue by chrtannus** [cytoscape/enrichment-map-webapp#294]
**Describe the bug**

On desktop and tablet screens, the user can click the **EM** icon to go back to the home screen and then create a new network or open another recent one:
<img width="616" alt="tablet-header" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/436a8092-55a0-46de-86c5-a24e48a2d811">

On mobile screens, the **EM** icon is hidden, because the network name and left/right drawer buttons take the whole header space--e.g. iPhone X:
<img width="386" alt="iPhoneX" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/a59cca78-3add-416e-b684-12bf48cbb09e">

The user can also use the browser's back button to go back to the home page but only if they started there. That's not possible if they got to the network page directly through a link.

**Expected behavior**

It should be easy or at least possible for a user to go to the home page from the network editor, no matter the screen size.

**Comment by chrtannus** [comment]
We could still add the EM icon to the header, but I'm afraid it would look too cramped, specially on very narrow screens:

<img width="397" alt="iPhone6" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/aa81793c-3715-409a-9e2b-55943abc8e9f">

**Comment by chrtannus** [comment]
Another option is to add the EM icon to the mobile menu:

<img width="400" alt="iPhone6-b" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/9500b9eb-60ec-48f2-a952-a7e9788b195c">

**Comment by mikekucera** [comment]
I don't think the icon in the menu is clear as to what it does. I'd say its better to put it in the header even though it takes up some space. Its consistent with the way it works on desktop and its more obvious.
