### ISSUE TITLE
Title editing doesn't seem to activate

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#30]
**Describe the bug**

Tapping on the title doesn't activate the text box for editing in the mobile simulator in Chrome.

**To Reproduce**

1. Open the UI in Chrome.
2. Open the debugger window.
3. Click the mobile simulator button at the top-left of the window.  See below.
4. Enable iPhone XR.  This is a typical phone screen size.
5. Try tapping the title.  Note that the text box doesn't open.

Mobile simulator button:

<img width="342" alt="Screen Shot 2022-10-20 at 08 53 22" src="https://user-images.githubusercontent.com/989043/196954181-b0073460-b2c2-4023-bf6d-de8b2b12d71b.png">

Chrome simulates mobile Chrome on Android behaviour, mostly.  The iPhone selection is mostly just for screen size.  

Usually, the Chrome debugging mobile mode can replicate some bugs, but it's not exactly the same as even an Android, unfortunately.  In any case, we should try this out on at least one iPhone and one Android phone to see how actual hardware is affected.

On the plus side, the UI itself seems to fit fairly well in an iPhone-sized screen.

**Expected behavior**

Open the text box for editing.

**Screenshots**

https://user-images.githubusercontent.com/989043/196955449-b510b724-38c8-48e0-8778-5909454bc0fd.mov

**Desktop (please complete the following information):**
 - OS: Mac 12.6
 - Browser: Chrome 
 - Version 105.0.5195.125 (Official Build) (arm64)
 - Simulating mobile with iPhone-XR-sized screen

**Additional context**

I'll update this with results from a physical iPhone, but I don't have an Android.

**Comment by maxkfranz** [comment]
Same thing on real iOS:


https://user-images.githubusercontent.com/989043/196957523-d89c833d-b1b4-4a8e-9283-3ad1b461d04d.mov

**Comment by chrtannus** [comment]
It's now easy to make the title editor enabled again and finally working, since the datastore function for updating the network name has been implemented. So I'm reopening this issue.

**Comment by maxkfranz** [comment]
Looks good now
