### ISSUE TITLE
Improved validation of input files

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#42]
**Description of new feature**

Common problems with input files should be detected by the app, and the user should get clear feedback for how to resolve the issues in their data.

**Motivation for new feature**

There may be inconsistencies (lack of standardisation) in the data, and without proper guidance users will tend to just give up and leave.

**Comment by maxkfranz** [comment]
25s end-to-end, or 25s just piping the data in express?

**Comment by mikekucera** [comment]
25s end-to-end, from clicking Submit to seeing a network

**Comment by mikekucera** [comment]
The majority of that is in the R service, calculating the ranks. Both the FGSEA part and the EM part are pretty fast. 25s seems pretty good to me, but of course that number is in a dev environment on my machine so maybe not applicable to a production environment.

**Comment by maxkfranz** [comment]
Yeah, we’ll have to see what it’s like on a prod environment.  Do Ruth’s and Veronique’s files have a typical size?

**Comment by maxkfranz** [comment]
Closing. Use new issues as particular problems come up
