### ISSUE TITLE
Drag-and-drop of GCT file does not work (in Chrome).

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#59]
**Describe the bug**
Dragging and dropping a .GCT file on the landing page doesn't work in Chrome. 
Instead of loading the file it opens a new browser tab with the contents of the file displayed. 
I assume this is a browser issue with Chrome because it works as expected in Safari. 
Opening the same file using the "Enrich my RNA-seq Data" button works fine.

**To Reproduce**
Try to drag and drop a .GCT expression file onto the landing page in Chrome. (Contact me if you need a .GCT file, or use the one Veronique sent on Dec 7, I don't want to post the link here publicly).

**Expected behavior**
Should take me to the Class Chooser UI.

**Comment by maxkfranz** [comment]
@mikekucera, the GCT extension was added to the whitelist so this can be closed, right?

**Comment by mikekucera** [comment]
yes
