### ISSUE TITLE
Clicking browser back button on Class Chooser should take me back to the landing page.

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#60]
**Description of new feature**

I start by going to the landing page. Then I upload an expression file. This takes me to the Class Chooser UI. Clicking the browser back button at this point should take me back to the landing page. Instead it takes me back to the page I was looking at before going to the landing page. Basically it removes me from the site entirely. This is actually really annoying.

Alternatively we could have a "Cancel" button on the class chooser in addition to the "Submit" button. But I still tend to go for the back button out of pure muscle memory.

**Motivation for new feature**

When uploading an expression file it looks like I've navigated to a new page when it shows the Class Chooser. But the implementation is actually still on the same page, it got re-rendered because uploading the file changed the component state, but didn't actually navigate to a new page.

**Comment by maxkfranz** [comment]
If we support the back button (history support), we should also consider the forwards button.  What would happen if a user goes back from the class chooser to the upload UI and then they hit the forward button?

Some options:

(1) If they hit back, the forward button does work.  You are returned to the class chooser with all its state preserved.

- Pro: Intuitive
- Con: URL handling is complex.  The URL must have all state in it or have enough info to rebuild the state fully.
- Con: URLs aren't shareable

(2) If they hit back, the forward button doesn't work (i.e. the history entry is deleted).  The user would have to upload the data over again.

- Pro:  
- Con:  If you go directly to a URL like /class-selector-ui, what do we show?  There's no state that can be rebuilt.
- Con: URLs aren't shareable

(3) Leave it as-is

- Pro: No URL complications
- Con: You can't use the back button from the class selector

(4) Leave it as-is w.r.t. history / back button, but add an in-UI 'back to upload' button

- Pro:  No URL complications
- Con:  Some people may still try the history feature (e.g. swipe to go back)
- Pro:  A lot of people may not even try the browser's back button, but they would more easily notice an in-UI button

**Comment by mikekucera** [comment]
My vote is option 4. The state of the Content component can include the entire file that was uploaded. Encoding that in a URL is probably not possible.
