### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#64]
**Description of new feature**

Add a favicon that shows up in browser tab. Probably just a small version of the EM icon from the front page.

**Motivation for new feature**

All websites have favicons :)

**Comment by maxkfranz** [comment]
Not for now, but maybe for later:  Dynamic favicons can give a great UX for showing status if a user switches tabs (e.g. email apps can show the unread message count).  Some users may switch tabs if a query takes longer than a few seconds, so we might use the favicon to show the loading status of the query in addition to the tab title.
