### ISSUE TITLE
FGSEA and EM services can return warnings or diagnostic messages.

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#69]
**Description of new feature**

Add fields to the returned Json data from the microservices that carries warnings or diagnostic messages. The express server can then log these messages, warn the user, or send them to Sentry.

I propose that for now the microservices don't directly integrate with Sentry. Instead they send messages back to the express server and it can send them to Sentry if needed. 
Reasons for this approach are: 
1) there is no R SDK for Sentry, so it would be difficult to integrate that service with Sentry. (Theoretically it could send a request to Sentry's HTTP API using the R equivalent of curl, but that would be messy.)
2) Localize the dependency on the Sentry SDK to our javascript code.
3) It would be strange if the Java service directly contacted Sentry but the R service did not.

Proposal to add a "messages" field to the returned Json from both services. This field would be an array of Message objects of the form...

```
{
   level: <string, one of "warning", "info", "error" etc...>,
   type: <string, indicates the type of error, eg "non_fininte_ranks">,
   text: <string, freeform text that will be logged>,
   data: { object containing additional data, structure depends on the 'type' field }
}
```

**Motivation for new feature**

Its possible for the ranks calculation in the R service to produce non-finite values. These then have to be filtered out before passing the ranks to the FGSEA function. We want to know how often non-finite values are being produced by the ranks calculation to determine if it is a real problem. We don't want to return just an error code from the R service because the network can still be created even if some ranks had to be discarded. 

More generally in the future there may be all kinds of warnings or other info produced by the services that could be used in a variety of ways.

**Comment by maxkfranz** [comment]
@mikekucera, can this be closed?

**Comment by mikekucera** [comment]
The only diagnostic info returned at the moment is from the FGSEA ranks calculation. But the capability is now there for the services to return any messages we may need in the future. So yes I think this can be closed and we can open new issues as needed.
