### ISSUE TITLE
better progress reporting while network is being generated

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#85]
**Description of new feature**

- Let the user know how long they have to wait to get the result.
- A faked progress bar?
- Just say, 'under a 60 seconds'.
- Show a notification?
  - Downside: permission

**Motivation for new feature**

- I have no idea how long the app should take.
- It takes longer than a few seconds, so I leave.

**Comment by mikekucera** [comment]
A faked progress bar is not a terrible idea. Netflix does this. I've noticed many times when Netflix is buffering the percentage slowly increases, until it gets to some value, and then pauses, even though the video never loads. This keeps you waiting thinking its going to actually work!

**Comment by maxkfranz** [comment]
Faked progress bars work really well when you overshoot the estimated duration a bit.  Aim for the worst case duration.  The last bit of progress might go at a faster speed than the first part, since you’ve actually got the query response before the bar has finished.  That’s not as smooth an accurate duration estimate, but it can feel like a bonus to the user:  It went faster than I expected for the last bit.  Bonus!

The thing to try to avoid with a progress bar is undershooting the duration.  It’s really annoying when the progress bar stops moving.  Is it frozen?  Is it broken?  I feel ripped off.  Maybe I’ll leave…

Do we already have a way to track how long an end-to-end query takes?  Maybe something like a custom google analytics metric?  We could make an educated guess for now and then refine the estimate based on what the real worst case is in practice in the long term.

**Comment by maxkfranz** [comment]
Just adding one note re. prioritisation:  A progress bar is nice to have, but there’s a lot of other, important things to do.  Even just text like ‘your results will be ready in under 60 seconds’ would be enough to start.

**Comment by maxkfranz** [comment]
If we're going with the simple text approach for now (i.e. the spinner has text beside it that says 'Your result will be ready in under a minute'), then we'll need a new issue for tracking more sophisticated approaches for future (e.g. a progress bar).

**Comment by maxkfranz** [comment]
- Add stats for input proxy measures / stats (input file size) and query duration in MongoDB for the network. Estimation later
- Text 'takes about a minute' and/or fake progress bar with hard-coded upper-limit time estimate

**Comment by maxkfranz** [comment]
Do we currently state the ~1min query response time in the UI now?
