### ISSUE TITLE
Describe what the gene scores are

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#89]
**Description of new feature**

- Some people will want to know exactly what the genes scores are.  Which metric is it?
- FAQ?
- Help documentation?
- Tooltip on bar?

**Motivation for new feature**

Some users really want to be sure about this.

**Comment by maxkfranz** [comment]
The tooltip might be interesting also for the edge cases where the score is harder to read.  The tooltip could read something like:

> Metric X: 1.23

**Comment by mikekucera** [comment]
FGSEA paper: https://www.frontiersin.org/articles/10.3389/fgene.2021.577623/full
EM Protocol: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6607905/

**Comment by mikekucera** [comment]
The ranks represent "differential gene expression". They give each gene a value based on if it was more expressed (up-regulated, positive) or less expressed (down-regulated, negative) between the two experiments that are being compared. The GSEA algorithm then uses that list, and a database of gene sets, to determine which gene sets are overall more or less expressed (or enriched?). So if a gene set contains a lot of the up-regulated genes then the gene set likely gets a high enrichment score (NES stands for normalized enrichment score, I'm not sure how the normalization works). 

We also compress clusters of similar gene sets into a "compound" node and take the average of the NES values. I think similar gene sets will naturally have similar NES values, so I think taking the average is safe.

**Comment by mikekucera** [comment]
I think we should consider having a separate FAQ/Wiki page that describes how the application works and what the numbers mean, and just link out to it. That way it can contain as much information as necessary without cluttering the app UI, and we can update it without having to update the application itself. This GeneMANIA help site is an example: http://pages.genemania.org/help/

**Comment by maxkfranz** [comment]
We could use a markdown file in the repo or a github wiki to start

**Comment by maxkfranz** [comment]
How about this for now?

Tooltip on hover of gene score bar:

> Differential gene expression: 1.23 (up-regulated)

**Comment by mikekucera** [comment]
The EnrichmentMap protocol paper describes the ranks like this...

> (iii) effect size and direction of expression change so that upregulated genes are positive and at the top of the list and downregulated genes are negative and at the bottom of the list, often expressed as log-transformed fold-change. The gene list is then ranked by one or more of these values **(e.g., —log10 P value multiplied by the sign of log-transformed fold-change)** 

This is indeed what we are doing in the R code...

```
ranks = sign(table_res$table$logFC) * -log10(table_res$table$PValue)
```

So maybe the tooltip could say something like "rank represents differential gene expression, expressed as —log10 pvalue multiplied by sign of log-transformed fold-change".  Or maybe that's too complicated I don't know.

**Comment by chrtannus** [comment]
The tooltip so far:

**Desktop:**
<img width="631" alt="rank-tooltip-desktop" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/84acd318-655b-4880-aa03-84a52ed2914f">

**Mobile:**
<img width="415" alt="rank-tooltip-mobile" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/cf61b07a-1111-4bc4-91e7-0b23073ac281">
