### ISSUE TITLE
Gene score digits not displayed

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#90]
**Describe the bug**

Sometimes the score is a whole number, like 7.  This gets shown as `7` instead of `7.00`, like the other scores.

The problem with this is that, to a user, it looks like we may have erroneously rounded the number.

**To Reproduce**

I can provide a file to reproduce this, if needed.

**Expected behavior**

Pad the number so it’s always `X.YZ’

**Comment by chrtannus** [comment]
Done! I think we can close this one now.
