### ISSUE TITLE
Image export should not include temporary state

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#93]
**Describe the bug**

When an image export is made, temporary state is included (e.g. highlight).

**To Reproduce**
1. Go to any result
2. Click on a node
3. Export the network image
4. See the highlight is applied in the image

**Expected behavior**

The highlight should not be in the image, nor should any other temporary state.  Each state should correspond to Cytoscape CSS classes.  Just remove those classes and restore them after the export.

**Comment by mikekucera** [comment]
I believe this is fixed.
